name: deploy-prod

on:
  push:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to EC2
        run: |
          chmod og= $SSH_PRIVATE_KEY
          ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $DEPLOY_USER@$PROD1_IP "cd /opt/bitnami/apps/wordpress && git checkout production && git pull && exit"
          ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $DEPLOY_USER@$PROD1_IP "cd /opt/bitnami/apps/wordpress && wp config set FHUB_RELEASE_TIMESTAMP $GITHUB_RUN_ID"
          ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $DEPLOY_USER@$PROD1_IP "cd /opt/bitnami/apps/wordpress && wp w3-total-cache flush all"
