name: deploy-prod

on:
  push:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PROD1_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/bitnami/apps/wordpress
            git checkout production
            git pull
            wp config set FHUB_RELEASE_TIMESTAMP $GITHUB_RUN_ID
            wp w3-total-cache flush all
